import type { Id } from "../../convex/_generated/dataModel";
import type { DemoFloorState } from "./types";

export const DEMO_VIEWER_ID = "demo_staff_jon";

export function createDemoFloorState(): DemoFloorState {
	return {
		profile: {
			id: DEMO_VIEWER_ID,
			name: "Toby Scott",
			role: "supervisor",
			roleTitle: "Floor Coordinator",
			sectionName: "Main Hall",
			sectionId: "section-main-hall",
			isSupervisor: true,
			eventDate: "2026-04-22T00:00:00.000Z",
			sectionStartTime: "09:00",
			sectionEndTime: "17:00",
		},
		nextJobTicket: 7,
		jobs: [
			{
				id: "demo_job_1",
				ticketNumber: 1,
				creatorId: "demo_staff_maria",
				personCount: 1,
				requestType: "vip",
				description: "Speaker entourage",
				status: "pending",
				creatorName: "Maria Santos",
				creatorRole: "usher",
				creatorRoleTitle: "Usher Lead",
				claimerRoleTitle: "",
				originSectionName: "gate a",
				creatorMissing: false,
				claimerMissing: false,
			},
			{
				id: "demo_job_2",
				ticketNumber: 2,
				creatorId: DEMO_VIEWER_ID,
				personCount: 4,
				requestType: "family",
				description: "Late arrivals",
				status: "pending",
				creatorName: "Toby Scott",
				creatorRole: "supervisor",
				creatorRoleTitle: "Floor Coordinator",
				claimerRoleTitle: "",
				originSectionName: "main hall",
				creatorMissing: false,
				claimerMissing: false,
			},
			{
				id: "demo_job_3",
				ticketNumber: 3,
				creatorId: DEMO_VIEWER_ID,
				claimerId: "demo_staff_david",
				personCount: 2,
				requestType: "wheelchair",
				description: "Needs ramp access",
				status: "accepted",
				creatorName: "Toby Scott",
				creatorRole: "supervisor",
				creatorRoleTitle: "Floor Coordinator",
				claimerName: "David Park",
				claimerRole: "staff",
				claimerRoleTitle: "Queue Usher",
				originSectionName: "main hall",
				destinationSectionName: "gate a",
				creatorMissing: false,
				claimerMissing: false,
			},
			{
				id: "demo_job_4",
				ticketNumber: 4,
				creatorId: "demo_staff_james",
				claimerId: "demo_staff_elena",
				personCount: 1,
				requestType: "vip",
				description: "Press photographer",
				status: "accepted",
				creatorName: "James Wu",
				creatorRole: "supervisor",
				creatorRoleTitle: "Gate Supervisor",
				claimerName: "Elena Reyes",
				claimerRole: "supervisor",
				claimerRoleTitle: "VIP Host",
				originSectionName: "gate a",
				destinationSectionName: "vip lounge",
				creatorMissing: false,
				claimerMissing: false,
			},
			{
				id: "demo_job_5",
				ticketNumber: 5,
				creatorId: "demo_staff_priya",
				personCount: 1,
				requestType: "elderly",
				description: "Guest needs escort to seats",
				status: "pending",
				creatorName: "Priya Nair",
				creatorRole: "staff",
				creatorRoleTitle: "Door Attendant",
				claimerRoleTitle: "",
				originSectionName: "main hall",
				creatorMissing: false,
				claimerMissing: false,
			},
			{
				id: "demo_job_6",
				ticketNumber: 6,
				creatorId: "demo_staff_elena",
				claimerId: "demo_staff_maria",
				personCount: 3,
				requestType: "regular",
				description: "Lost group from coat check",
				status: "accepted",
				creatorName: "Elena Reyes",
				creatorRole: "supervisor",
				creatorRoleTitle: "VIP Host",
				claimerName: "Maria Santos",
				claimerRole: "staff",
				claimerRoleTitle: "Usher Lead",
				originSectionName: "vip lounge",
				destinationSectionName: "main hall",
				creatorMissing: false,
				claimerMissing: false,
			},
		],
		alerts: [
			{
				id: "demo_alert_1",
				creatorId: "demo_staff_james",
				creatorName: "James Wu",
				creatorRole: "supervisor",
				creatorRoleTitle: "Gate Supervisor",
				sectionName: "gate a",
				alertType: "crowd_control",
				body: "Queue backing up at Gate A — need two more ushers.",
				status: "open",
				isPinned: false,
				createdAt: Date.now() - 1000 * 60 * 8,
				updates: [
					{
						id: "demo_alert_update_1",
						authorId: "demo_staff_david",
						authorName: "David Park",
						authorRole: "staff",
						content: "On my way from VIP lounge.",
						createdAt: Date.now() - 1000 * 60 * 5,
					},
				],
			},
		],
		watchlist: [
			{
				id: "demo_watchlist_1",
				kind: "banned_person",
				label: "Jon Doe",
				notes: "Do not admit. Last seen wearing a dark jacket near Gate A.",
				photoUrl: "/demo/banned-person.png",
				updates: [
					{
						id: "demo_watchlist_update_1",
						authorId: "demo_staff_james",
						authorName: "James Wu",
						content: "Spotted near the queue — security notified.",
						createdAt: Date.now() - 1000 * 60 * 12,
					},
				],
			},
			{
				id: "demo_watchlist_2",
				kind: "prohibited_item",
				label: "Alcoholic drinks",
				notes: "No alcohol is permitted on the premises of this venue.",
				photoUrl: "/demo/prohibited-beer.png",
				updates: [
					{
						id: "demo_watchlist_update_2",
						authorId: "demo_staff_maria",
						authorName: "Maria Santos",
						content: "👍",
						createdAt: Date.now() - 1000 * 60 * 9,
					},
					{
						id: "demo_watchlist_update_3",
						authorId: "demo_staff_priya",
						authorName: "Priya Nair",
						content: "Acknowledged",
						createdAt: Date.now() - 1000 * 60 * 6,
					},
				],
			},
		],
		sections: [
			{
				sectionKey: "section-main-hall",
				name: "main hall",
				startTime: "09:00",
				endTime: "17:00",
				headcountReporting: true,
				includeInTotal: true,
				headcount: 420,
				activity: "busy",
				occupancyFill: "75",
				slots: [
					{
						rowKey: "mh-1",
						title: "Floor Coordinator",
						role: "supervisor",
						assignedStaffId: DEMO_VIEWER_ID as Id<"liveStaff">,
						staffName: "Toby Scott",
						staffStatus: "active",
						isViewer: true,
					},
					{
						rowKey: "mh-2",
						title: "Usher Lead",
						role: "staff",
						assignedStaffId: "demo_staff_maria" as Id<"liveStaff">,
						staffName: "Maria Santos",
						staffStatus: "active",
						isViewer: false,
					},
					{
						rowKey: "mh-3",
						title: "Door Attendant",
						role: "staff",
						assignedStaffId: "demo_staff_priya" as Id<"liveStaff">,
						staffName: "Priya Nair",
						staffStatus: "active",
						isViewer: false,
					},
				],
			},
			{
				sectionKey: "section-gate-a",
				name: "gate a",
				startTime: "08:30",
				endTime: "16:30",
				headcountReporting: true,
				includeInTotal: true,
				headcount: 280,
				activity: "overload",
				occupancyFill: "90",
				slots: [
					{
						rowKey: "ga-1",
						title: "Gate Supervisor",
						role: "supervisor",
						assignedStaffId: "demo_staff_james" as Id<"liveStaff">,
						staffName: "James Wu",
						staffStatus: "active",
						isViewer: false,
					},
					{
						rowKey: "ga-2",
						title: "Queue Usher",
						role: "staff",
						assignedStaffId: "demo_staff_david" as Id<"liveStaff">,
						staffName: "David Park",
						staffStatus: "active",
						isViewer: false,
					},
				],
			},
			{
				sectionKey: "section-vip",
				name: "vip lounge",
				startTime: "10:00",
				endTime: "14:00",
				headcountReporting: true,
				includeInTotal: true,
				headcount: 85,
				activity: "normal",
				occupancyFill: "50",
				slots: [
					{
						rowKey: "vip-1",
						title: "VIP Host",
						role: "supervisor",
						assignedStaffId: "demo_staff_elena" as Id<"liveStaff">,
						staffName: "Elena Reyes",
						staffStatus: "active",
						isViewer: false,
					},
				],
			},
		],
	};
}
