/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as LiveRouteRouteImport } from './routes/live/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as LiveEndedRouteImport } from './routes/live/ended'
import { Route as LiveInviteTokenRouteImport } from './routes/live/$inviteToken'
import { Route as LiveDashboardRouteRouteImport } from './routes/live/_dashboard/route'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as LiveDashboardIndexRouteImport } from './routes/live/_dashboard/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as LiveDashboardRosterRouteImport } from './routes/live/_dashboard/roster'
import { Route as LiveDashboardJobsRouteImport } from './routes/live/_dashboard/jobs'
import { Route as LiveDashboardAlertRouteImport } from './routes/live/_dashboard/alert'
import { Route as LiveDashboardAdminRouteImport } from './routes/live/_dashboard/admin'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedAppSuccessRouteImport } from './routes/_authenticated/app/success'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app/settings'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app/dashboard'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app/billing'
import { Route as publicauthSignupRouteImport } from './routes/(public)/(auth)/signup'
import { Route as publicauthSigninRouteImport } from './routes/(public)/(auth)/signin'
import { Route as AuthenticatedAppEventsIndexRouteImport } from './routes/_authenticated/app/events/index'
import { Route as AuthenticatedAppEventsCreateRouteImport } from './routes/_authenticated/app/events/create'
import { Route as AuthenticatedAppEventsEventIdIndexRouteImport } from './routes/_authenticated/app/events/$eventId/index'
import { Route as AuthenticatedAppEventsEventIdWatchlistRouteImport } from './routes/_authenticated/app/events/$eventId/watchlist'
import { Route as AuthenticatedAppEventsEventIdEditRouteImport } from './routes/_authenticated/app/events/$eventId/edit'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRouteRoute = LiveRouteRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const LiveEndedRoute = LiveEndedRouteImport.update({
  id: '/ended',
  path: '/ended',
  getParentRoute: () => LiveRouteRoute,
} as any)
const LiveInviteTokenRoute = LiveInviteTokenRouteImport.update({
  id: '/$inviteToken',
  path: '/$inviteToken',
  getParentRoute: () => LiveRouteRoute,
} as any)
const LiveDashboardRouteRoute = LiveDashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => LiveRouteRoute,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_authenticated/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveDashboardIndexRoute = LiveDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LiveDashboardRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const LiveDashboardRosterRoute = LiveDashboardRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => LiveDashboardRouteRoute,
} as any)
const LiveDashboardJobsRoute = LiveDashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => LiveDashboardRouteRoute,
} as any)
const LiveDashboardAlertRoute = LiveDashboardAlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => LiveDashboardRouteRoute,
} as any)
const LiveDashboardAdminRoute = LiveDashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LiveDashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSuccessRoute = AuthenticatedAppSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const publicauthSignupRoute = publicauthSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicauthSigninRoute = publicauthSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => publicRouteRoute,
} as any)
const AuthenticatedAppEventsIndexRoute =
  AuthenticatedAppEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppEventsCreateRoute =
  AuthenticatedAppEventsCreateRouteImport.update({
    id: '/events/create',
    path: '/events/create',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppEventsEventIdIndexRoute =
  AuthenticatedAppEventsEventIdIndexRouteImport.update({
    id: '/events/$eventId/',
    path: '/events/$eventId/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppEventsEventIdWatchlistRoute =
  AuthenticatedAppEventsEventIdWatchlistRouteImport.update({
    id: '/events/$eventId/watchlist',
    path: '/events/$eventId/watchlist',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppEventsEventIdEditRoute =
  AuthenticatedAppEventsEventIdEditRouteImport.update({
    id: '/events/$eventId/edit',
    path: '/events/$eventId/edit',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/live': typeof LiveDashboardRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/live/$inviteToken': typeof LiveInviteTokenRoute
  '/live/ended': typeof LiveEndedRoute
  '/': typeof publicIndexRoute
  '/signin': typeof publicauthSigninRoute
  '/signup': typeof publicauthSignupRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/success': typeof AuthenticatedAppSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/live/admin': typeof LiveDashboardAdminRoute
  '/live/alert': typeof LiveDashboardAlertRoute
  '/live/jobs': typeof LiveDashboardJobsRoute
  '/live/roster': typeof LiveDashboardRosterRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/live/': typeof LiveDashboardIndexRoute
  '/app/events/create': typeof AuthenticatedAppEventsCreateRoute
  '/app/events/': typeof AuthenticatedAppEventsIndexRoute
  '/app/events/$eventId/edit': typeof AuthenticatedAppEventsEventIdEditRoute
  '/app/events/$eventId/watchlist': typeof AuthenticatedAppEventsEventIdWatchlistRoute
  '/app/events/$eventId/': typeof AuthenticatedAppEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/live': typeof LiveDashboardIndexRoute
  '/demo': typeof DemoRoute
  '/live/$inviteToken': typeof LiveInviteTokenRoute
  '/live/ended': typeof LiveEndedRoute
  '/': typeof publicIndexRoute
  '/signin': typeof publicauthSigninRoute
  '/signup': typeof publicauthSignupRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/success': typeof AuthenticatedAppSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/live/admin': typeof LiveDashboardAdminRoute
  '/live/alert': typeof LiveDashboardAlertRoute
  '/live/jobs': typeof LiveDashboardJobsRoute
  '/live/roster': typeof LiveDashboardRosterRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/events/create': typeof AuthenticatedAppEventsCreateRoute
  '/app/events': typeof AuthenticatedAppEventsIndexRoute
  '/app/events/$eventId/edit': typeof AuthenticatedAppEventsEventIdEditRoute
  '/app/events/$eventId/watchlist': typeof AuthenticatedAppEventsEventIdWatchlistRoute
  '/app/events/$eventId': typeof AuthenticatedAppEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/live': typeof LiveRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/live/_dashboard': typeof LiveDashboardRouteRouteWithChildren
  '/live/$inviteToken': typeof LiveInviteTokenRoute
  '/live/ended': typeof LiveEndedRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/(auth)/signin': typeof publicauthSigninRoute
  '/(public)/(auth)/signup': typeof publicauthSignupRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/success': typeof AuthenticatedAppSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/live/_dashboard/admin': typeof LiveDashboardAdminRoute
  '/live/_dashboard/alert': typeof LiveDashboardAlertRoute
  '/live/_dashboard/jobs': typeof LiveDashboardJobsRoute
  '/live/_dashboard/roster': typeof LiveDashboardRosterRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/live/_dashboard/': typeof LiveDashboardIndexRoute
  '/_authenticated/app/events/create': typeof AuthenticatedAppEventsCreateRoute
  '/_authenticated/app/events/': typeof AuthenticatedAppEventsIndexRoute
  '/_authenticated/app/events/$eventId/edit': typeof AuthenticatedAppEventsEventIdEditRoute
  '/_authenticated/app/events/$eventId/watchlist': typeof AuthenticatedAppEventsEventIdWatchlistRoute
  '/_authenticated/app/events/$eventId/': typeof AuthenticatedAppEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/live'
    | '/demo'
    | '/app'
    | '/live/$inviteToken'
    | '/live/ended'
    | '/'
    | '/signin'
    | '/signup'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/success'
    | '/api/auth/$'
    | '/live/admin'
    | '/live/alert'
    | '/live/jobs'
    | '/live/roster'
    | '/app/'
    | '/live/'
    | '/app/events/create'
    | '/app/events/'
    | '/app/events/$eventId/edit'
    | '/app/events/$eventId/watchlist'
    | '/app/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/live'
    | '/demo'
    | '/live/$inviteToken'
    | '/live/ended'
    | '/'
    | '/signin'
    | '/signup'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/success'
    | '/api/auth/$'
    | '/live/admin'
    | '/live/alert'
    | '/live/jobs'
    | '/live/roster'
    | '/app'
    | '/app/events/create'
    | '/app/events'
    | '/app/events/$eventId/edit'
    | '/app/events/$eventId/watchlist'
    | '/app/events/$eventId'
  id:
    | '__root__'
    | '/(public)'
    | '/live'
    | '/demo'
    | '/_authenticated/app'
    | '/live/_dashboard'
    | '/live/$inviteToken'
    | '/live/ended'
    | '/(public)/'
    | '/(public)/(auth)/signin'
    | '/(public)/(auth)/signup'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/success'
    | '/api/auth/$'
    | '/live/_dashboard/admin'
    | '/live/_dashboard/alert'
    | '/live/_dashboard/jobs'
    | '/live/_dashboard/roster'
    | '/_authenticated/app/'
    | '/live/_dashboard/'
    | '/_authenticated/app/events/create'
    | '/_authenticated/app/events/'
    | '/_authenticated/app/events/$eventId/edit'
    | '/_authenticated/app/events/$eventId/watchlist'
    | '/_authenticated/app/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  LiveRouteRoute: typeof LiveRouteRouteWithChildren
  DemoRoute: typeof DemoRoute
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/live/ended': {
      id: '/live/ended'
      path: '/ended'
      fullPath: '/live/ended'
      preLoaderRoute: typeof LiveEndedRouteImport
      parentRoute: typeof LiveRouteRoute
    }
    '/live/$inviteToken': {
      id: '/live/$inviteToken'
      path: '/$inviteToken'
      fullPath: '/live/$inviteToken'
      preLoaderRoute: typeof LiveInviteTokenRouteImport
      parentRoute: typeof LiveRouteRoute
    }
    '/live/_dashboard': {
      id: '/live/_dashboard'
      path: ''
      fullPath: '/live'
      preLoaderRoute: typeof LiveDashboardRouteRouteImport
      parentRoute: typeof LiveRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/_dashboard/': {
      id: '/live/_dashboard/'
      path: '/'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveDashboardIndexRouteImport
      parentRoute: typeof LiveDashboardRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/live/_dashboard/roster': {
      id: '/live/_dashboard/roster'
      path: '/roster'
      fullPath: '/live/roster'
      preLoaderRoute: typeof LiveDashboardRosterRouteImport
      parentRoute: typeof LiveDashboardRouteRoute
    }
    '/live/_dashboard/jobs': {
      id: '/live/_dashboard/jobs'
      path: '/jobs'
      fullPath: '/live/jobs'
      preLoaderRoute: typeof LiveDashboardJobsRouteImport
      parentRoute: typeof LiveDashboardRouteRoute
    }
    '/live/_dashboard/alert': {
      id: '/live/_dashboard/alert'
      path: '/alert'
      fullPath: '/live/alert'
      preLoaderRoute: typeof LiveDashboardAlertRouteImport
      parentRoute: typeof LiveDashboardRouteRoute
    }
    '/live/_dashboard/admin': {
      id: '/live/_dashboard/admin'
      path: '/admin'
      fullPath: '/live/admin'
      preLoaderRoute: typeof LiveDashboardAdminRouteImport
      parentRoute: typeof LiveDashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/success': {
      id: '/_authenticated/app/success'
      path: '/success'
      fullPath: '/app/success'
      preLoaderRoute: typeof AuthenticatedAppSuccessRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/(public)/(auth)/signup': {
      id: '/(public)/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof publicauthSignupRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(auth)/signin': {
      id: '/(public)/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof publicauthSigninRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/_authenticated/app/events/': {
      id: '/_authenticated/app/events/'
      path: '/events'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AuthenticatedAppEventsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/events/create': {
      id: '/_authenticated/app/events/create'
      path: '/events/create'
      fullPath: '/app/events/create'
      preLoaderRoute: typeof AuthenticatedAppEventsCreateRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/events/$eventId/': {
      id: '/_authenticated/app/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/app/events/$eventId/'
      preLoaderRoute: typeof AuthenticatedAppEventsEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/events/$eventId/watchlist': {
      id: '/_authenticated/app/events/$eventId/watchlist'
      path: '/events/$eventId/watchlist'
      fullPath: '/app/events/$eventId/watchlist'
      preLoaderRoute: typeof AuthenticatedAppEventsEventIdWatchlistRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/events/$eventId/edit': {
      id: '/_authenticated/app/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/app/events/$eventId/edit'
      preLoaderRoute: typeof AuthenticatedAppEventsEventIdEditRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicauthSigninRoute: typeof publicauthSigninRoute
  publicauthSignupRoute: typeof publicauthSignupRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicauthSigninRoute: publicauthSigninRoute,
  publicauthSignupRoute: publicauthSignupRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface LiveDashboardRouteRouteChildren {
  LiveDashboardAdminRoute: typeof LiveDashboardAdminRoute
  LiveDashboardAlertRoute: typeof LiveDashboardAlertRoute
  LiveDashboardJobsRoute: typeof LiveDashboardJobsRoute
  LiveDashboardRosterRoute: typeof LiveDashboardRosterRoute
  LiveDashboardIndexRoute: typeof LiveDashboardIndexRoute
}

const LiveDashboardRouteRouteChildren: LiveDashboardRouteRouteChildren = {
  LiveDashboardAdminRoute: LiveDashboardAdminRoute,
  LiveDashboardAlertRoute: LiveDashboardAlertRoute,
  LiveDashboardJobsRoute: LiveDashboardJobsRoute,
  LiveDashboardRosterRoute: LiveDashboardRosterRoute,
  LiveDashboardIndexRoute: LiveDashboardIndexRoute,
}

const LiveDashboardRouteRouteWithChildren =
  LiveDashboardRouteRoute._addFileChildren(LiveDashboardRouteRouteChildren)

interface LiveRouteRouteChildren {
  LiveDashboardRouteRoute: typeof LiveDashboardRouteRouteWithChildren
  LiveInviteTokenRoute: typeof LiveInviteTokenRoute
  LiveEndedRoute: typeof LiveEndedRoute
}

const LiveRouteRouteChildren: LiveRouteRouteChildren = {
  LiveDashboardRouteRoute: LiveDashboardRouteRouteWithChildren,
  LiveInviteTokenRoute: LiveInviteTokenRoute,
  LiveEndedRoute: LiveEndedRoute,
}

const LiveRouteRouteWithChildren = LiveRouteRoute._addFileChildren(
  LiveRouteRouteChildren,
)

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSuccessRoute: typeof AuthenticatedAppSuccessRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppEventsCreateRoute: typeof AuthenticatedAppEventsCreateRoute
  AuthenticatedAppEventsIndexRoute: typeof AuthenticatedAppEventsIndexRoute
  AuthenticatedAppEventsEventIdEditRoute: typeof AuthenticatedAppEventsEventIdEditRoute
  AuthenticatedAppEventsEventIdWatchlistRoute: typeof AuthenticatedAppEventsEventIdWatchlistRoute
  AuthenticatedAppEventsEventIdIndexRoute: typeof AuthenticatedAppEventsEventIdIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSuccessRoute: AuthenticatedAppSuccessRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppEventsCreateRoute: AuthenticatedAppEventsCreateRoute,
  AuthenticatedAppEventsIndexRoute: AuthenticatedAppEventsIndexRoute,
  AuthenticatedAppEventsEventIdEditRoute:
    AuthenticatedAppEventsEventIdEditRoute,
  AuthenticatedAppEventsEventIdWatchlistRoute:
    AuthenticatedAppEventsEventIdWatchlistRoute,
  AuthenticatedAppEventsEventIdIndexRoute:
    AuthenticatedAppEventsEventIdIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  LiveRouteRoute: LiveRouteRouteWithChildren,
  DemoRoute: DemoRoute,
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
