/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LiveRouteRouteImport } from './routes/live/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedAppSuccessRouteImport } from './routes/_authenticated/app/success'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app/dashboard'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app/billing'
import { Route as publicauthSignupRouteImport } from './routes/(public)/(auth)/signup'
import { Route as publicauthSigninRouteImport } from './routes/(public)/(auth)/signin'
import { Route as AuthenticatedAppEventsIndexRouteImport } from './routes/_authenticated/app/events/index'
import { Route as AuthenticatedAppEventsCreateRouteImport } from './routes/_authenticated/app/events/create'
import { Route as AuthenticatedAppEventsEventIdRouteImport } from './routes/_authenticated/app/events/$eventId'

const LiveRouteRoute = LiveRouteRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_authenticated/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSuccessRoute = AuthenticatedAppSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const publicauthSignupRoute = publicauthSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicauthSigninRoute = publicauthSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => publicRouteRoute,
} as any)
const AuthenticatedAppEventsIndexRoute =
  AuthenticatedAppEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppEventsCreateRoute =
  AuthenticatedAppEventsCreateRouteImport.update({
    id: '/events/create',
    path: '/events/create',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppEventsEventIdRoute =
  AuthenticatedAppEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/live': typeof LiveRouteRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/': typeof publicIndexRoute
  '/signin': typeof publicauthSigninRoute
  '/signup': typeof publicauthSignupRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/success': typeof AuthenticatedAppSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/events/$eventId': typeof AuthenticatedAppEventsEventIdRoute
  '/app/events/create': typeof AuthenticatedAppEventsCreateRoute
  '/app/events/': typeof AuthenticatedAppEventsIndexRoute
}
export interface FileRoutesByTo {
  '/live': typeof LiveRouteRoute
  '/': typeof publicIndexRoute
  '/signin': typeof publicauthSigninRoute
  '/signup': typeof publicauthSignupRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/success': typeof AuthenticatedAppSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/events/$eventId': typeof AuthenticatedAppEventsEventIdRoute
  '/app/events/create': typeof AuthenticatedAppEventsCreateRoute
  '/app/events': typeof AuthenticatedAppEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/live': typeof LiveRouteRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(public)/(auth)/signin': typeof publicauthSigninRoute
  '/(public)/(auth)/signup': typeof publicauthSignupRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/success': typeof AuthenticatedAppSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/events/$eventId': typeof AuthenticatedAppEventsEventIdRoute
  '/_authenticated/app/events/create': typeof AuthenticatedAppEventsCreateRoute
  '/_authenticated/app/events/': typeof AuthenticatedAppEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/live'
    | '/app'
    | '/'
    | '/signin'
    | '/signup'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/success'
    | '/api/auth/$'
    | '/app/'
    | '/app/events/$eventId'
    | '/app/events/create'
    | '/app/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/live'
    | '/'
    | '/signin'
    | '/signup'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/success'
    | '/api/auth/$'
    | '/app'
    | '/app/events/$eventId'
    | '/app/events/create'
    | '/app/events'
  id:
    | '__root__'
    | '/(public)'
    | '/live'
    | '/_authenticated/app'
    | '/(public)/'
    | '/(public)/(auth)/signin'
    | '/(public)/(auth)/signup'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/success'
    | '/api/auth/$'
    | '/_authenticated/app/'
    | '/_authenticated/app/events/$eventId'
    | '/_authenticated/app/events/create'
    | '/_authenticated/app/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  LiveRouteRoute: typeof LiveRouteRoute
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/success': {
      id: '/_authenticated/app/success'
      path: '/success'
      fullPath: '/app/success'
      preLoaderRoute: typeof AuthenticatedAppSuccessRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/(public)/(auth)/signup': {
      id: '/(public)/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof publicauthSignupRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(auth)/signin': {
      id: '/(public)/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof publicauthSigninRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/_authenticated/app/events/': {
      id: '/_authenticated/app/events/'
      path: '/events'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AuthenticatedAppEventsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/events/create': {
      id: '/_authenticated/app/events/create'
      path: '/events/create'
      fullPath: '/app/events/create'
      preLoaderRoute: typeof AuthenticatedAppEventsCreateRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/events/$eventId': {
      id: '/_authenticated/app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/app/events/$eventId'
      preLoaderRoute: typeof AuthenticatedAppEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicauthSigninRoute: typeof publicauthSigninRoute
  publicauthSignupRoute: typeof publicauthSignupRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicauthSigninRoute: publicauthSigninRoute,
  publicauthSignupRoute: publicauthSignupRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppSuccessRoute: typeof AuthenticatedAppSuccessRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppEventsEventIdRoute: typeof AuthenticatedAppEventsEventIdRoute
  AuthenticatedAppEventsCreateRoute: typeof AuthenticatedAppEventsCreateRoute
  AuthenticatedAppEventsIndexRoute: typeof AuthenticatedAppEventsIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppSuccessRoute: AuthenticatedAppSuccessRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppEventsEventIdRoute: AuthenticatedAppEventsEventIdRoute,
  AuthenticatedAppEventsCreateRoute: AuthenticatedAppEventsCreateRoute,
  AuthenticatedAppEventsIndexRoute: AuthenticatedAppEventsIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  LiveRouteRoute: LiveRouteRoute,
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
